In [ ]:
# CSV → Comma-Separated Values — A file that stores table data using comma , to separate values.
# TSV → Tab-Separated Values — A file that stores table data using tab \t to separate values.
# DSV → Delimiter-Separated Values — A file that stores table data using any symbol like | ; : to separate values.

In [79]:
# introduction to  pandas  --------->>>>>>>
# pandas  is  an  open-sorce library of python which is  used for  handel  data manipulations   
# “Data manipulation is the process of cleaning, organizing, and transforming data to make it suitable for analysis.”

In [80]:
# ! pip install pandas  
# uv add pandas    for  uv

In [81]:
import  pandas as  pd

In [82]:
# data structure of pandas : - 
# 1.(Series) :- it is the  one -dimensional array  and it returns only  values not column name.
# 2.(DataFrame) :- it is  the two - dimensional  array  and  it  returns values with  columns name   


# for check  server  response  200  or  not  
# import requests

# url = "https://wittyschool.org/bhilwara/"
# res = requests.get(url)

# print(res.status_code)
# if  200  then use instant  data SCRAPER

In [83]:
a=pd.Series([1,45,78,90])
a

0     1
1    45
2    78
3    90
dtype: int64

In [84]:
type(a)

pandas.core.series.Series

In [85]:
# task::: we have to create a dataframe  of  employee in which  column are 
# emp_id , emp_name, department,salary ,working_hors

In [86]:
d = {
    "emp_id" : ['A101','A102','A103','A104','A105','A106'],
    "emp_name" : ['sam','rahul','aniket','Gorav','mohit','karan'],
    "department" : ['IT','Operation','IT','IT','Operation','IT'],
    "salary":[20000,25000,35000,21000,40000,45000],
    "working_hors" : [8,8,9,9,9,8]
}

In [87]:
print(type(d))
d

<class 'dict'>

{'emp_id': ['A101', 'A102', 'A103', 'A104', 'A105', 'A106'],
 'emp_name': ['sam', 'rahul', 'aniket', 'Gorav', 'mohit', 'karan'],
 'department': ['IT', 'Operation', 'IT', 'IT', 'Operation', 'IT'],
 'salary': [20000, 25000, 35000, 21000, 40000, 45000],
 'working_hors': [8, 8, 9, 9, 9, 8]}

In [88]:
df = pd.DataFrame(d)

In [89]:
# (1.)how can we export our dataframe into csv(Comma-Separated Values) data ?
#  (2.) the  symbol  of  dot notation  is --->>> .    
# (3.)   .to_csv() or read like this (dot notation to underscore csv ) ---->>>> use for  file  export or  to_csv() means 
# export  your  data into csv file  
# (4.) to_csv('enter the csv  file  name  u  want create.csv(extension of  csv)')

In [90]:
df.to_csv('csv1.csv')
# now u  see file is creatred with  name  of  csv1 
# It also saves index (extra unwanted column)
# issue  is still  here which  is  unwanted column name so  for solve this  we use  index =  false

In [91]:
df.to_csv('full_csv.csv',index=False)  # index =  false  means  it  will remove  unwanted  column

In [92]:
# | Step     | Why                             |
# | -------- | ------------------------------- |
# | CSV → DF | To **analyze / modify data**    |
# | DF → CSV | To **save results permanently** |

#  or  

# We load CSV data into a DataFrame because a DataFrame allows us to perform analysis and modifications. 
# After processing, we export it back to CSV to store the updated data.

In [93]:
# 📥 Step 1: Read CSV(to  convert  csv to  df )
# df = pd.read_csv("data.csv")

# ⚙️ Step 2: Perform tasks on  df 
# df = df.dropna()
# df["salary"] *= 2

# 📤 Step 3: Save back to CSV (df to csv save )
# df.to_csv("new_data.csv", index=False)

# If we save a CSV file with the same name, the existing file will be overwritten by the new data.
# so  other name like  update_file ,new_file

In [94]:
# why  we save in csv  why  we  noit  keep  in only  df  ?
# ans  
# A DataFrame is temporary and exists in memory, while a CSV file is used for permanent storage.
# We save data to CSV so it can be reused, shared, and accessed later.

In [95]:
# how  to  import  csv data using pandas ?

In [96]:
# import os  
# os.getcwd()

In [97]:
df =  pd.read_csv("C:\\Users\\Admin\\pandas\\full_csv.csv")
df

  emp_id emp_name department  salary  working_hors
0   A101      sam         IT   20000             8
1   A102    rahul  Operation   25000             8
2   A103   aniket         IT   35000             9
3   A104    Gorav         IT   21000             9
4   A105    mohit  Operation   40000             9
5   A106    karan         IT   45000             8

In [98]:
df =  pd.read_csv("C:\\Users\\Admin\\pandas\\flipkart.csv")

In [99]:
df = df.drop(columns=["k7wcnx href","UCc1lI src","fRrrYo","fU6cHR","PZfbSE src","o2SIOJ","DTBslk 7","DTBslk 5","DTBslk 8","nvcpki","qYp2rh src"])
df.head(3)

,RG5Slk,MKiFS6,PvbNMB,PvbNMB 2,DTBslk,DTBslk 2,DTBslk 3,DTBslk 4,DTBslk 6,DTBslk 9,hZ3P6w,HZ0E6r,kRYCnD,HQe8jr
0,"Apple iPhone 12 (White, 64 GB)",4.6,"2,12,372 Ratings","13,887 Reviews",64 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A14 Bionic Chip with Next Generation Neural En...,Industry-leading IP68 Water Resistance,1 year warranty for phone and 1 year warranty ...,"₹49,900",Bank Offer,NaN,NaN
1,"Apple iPhone 12 (Blue, 64 GB)",4.6,"2,12,372 Ratings","13,887 Reviews",64 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A14 Bionic Chip with Next Generation Neural En...,Industry-leading IP68 Water Resistance,1 year warranty for phone and 1 year warranty ...,"₹49,900",Bank Offer,NaN,NaN
2,"Apple iPhone 12 (Black, 64 GB)",4.6,"2,12,372 Ratings","13,887 Reviews",64 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A14 Bionic Chip with Next Generation Neural En...,Industry-leading IP68 Water Resistance,1 year warranty for phone and 1 year warranty ...,"₹49,900",Bank Offer,NaN,NaN

In [100]:
# df = df.rename(columns={"old": "new"})
df = df.rename(columns={
    'RG5Slk'   : 'Product_Name',
    'MKiFS6'   : 'Rating',
    'PvbNMB'   : 'Total_Ratings',
    'PvbNMB 2' : 'Total_Reviews',
    'DTBslk'   : 'Storage',
    'DTBslk 2' : 'Display',
    'DTBslk 3' : 'Camera',
    'DTBslk 4' : 'Processor',
    'DTBslk 6' : 'Water_Resistance',
    'DTBslk 9' : 'Warranty',
    'hZ3P6w'   : 'Selling_Price',
    'HZ0E6r'   : 'Bank_Offer',
    'kRYCnD'   : 'Original_Price',
    'HQe8jr'   : 'Discount'
})

In [101]:
df.head(1)

,Product_Name,Rating,Total_Ratings,Total_Reviews,Storage,Display,Camera,Processor,Water_Resistance,Warranty,Selling_Price,Bank_Offer,Original_Price,Discount
0,"Apple iPhone 12 (White, 64 GB)",4.6,"2,12,372 Ratings","13,887 Reviews",64 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A14 Bionic Chip with Next Generation Neural En...,Industry-leading IP68 Water Resistance,1 year warranty for phone and 1 year warranty ...,"₹49,900",Bank Offer,NaN,NaN

In [102]:
df2 =  pd.read_csv("C:\\Users\\Admin\\pandas\\best_food.csv")
df2

,zReHs href,LC20lb,XNo5Ab src,VuuXrf,qLRx3b,ylgVCe,VwiC3b,VwiC3b 2,vzmbzf href,vzmbzf,kb0PBd href,uhHOwf src,yi40Hd,RDApEe
0,https://www.zomato.com/jaipur/gopalpura-restau...,"Gopalpura Restaurants, Jaipur","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",Zomato,https://www.zomato.com,› jaipur › gopalpura-restaurants,"Gopalpura Restaurants, Jaipur · · Clayb.orn ·...",Up & Up,https://www.zomato.com/jaipur/gopalpura-restau...,Read more,https://www.zomato.com/jaipur/gopalpura-restau...,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",NaN,NaN
1,https://www.justdial.com/Jaipur/Restaurants-in...,"Best Restaurants in Gopalpura Bypass, Jaipur","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",Justdial,https://www.justdial.com,› ... › 2121+ Listings,"Best Restaurants in Gopalpura Bypass, Jaipur -...",Sabjiwalas,https://www.justdial.com/Jaipur/Restaurants-in...,Read more,https://www.justdial.com/Jaipur/Restaurants-in...,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",4.0,"(3,44,646)"
2,https://www.eazydiner.com/jaipur/restaurants/g...,"Best Restaurants in Gopalpura, Jaipur","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",EazyDiner,https://www.eazydiner.com,› jaipur › gopalpura,"Best Restaurants in Gopalpura, Jaipur · · Bre...",Lighthouse,https://www.eazydiner.com/jaipur/restaurants/g...,Read more,https://www.eazydiner.com/jaipur/restaurants/g...,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",NaN,NaN
3,https://www.swiggy.com/city/jaipur/gopalpura-r...,"Best Restaurants In Gopalpura, Jaipur 2025","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",Swiggy,https://www.swiggy.com,› City › Jaipur,"Discover ! Explore Menus, Reviews, Ratings, Pr...",All Restaurants Serving In Gopalpura,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.tripadvisor.in/RestaurantsNear-g30...,Restaurants near Holiday Inn Express & Suites ...,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",Tripadvisor,https://www.tripadvisor.in,› ... › Jaipur Restaurants,Restaurants near Holiday Inn Express & Suites ...,1. Express Café & Bar Jaipur,https://www.tripadvisor.in/RestaurantsNear-g30...,Read more,NaN,NaN,NaN,NaN
5,https://www.jaipurmetroroutes.com/areas/gopalp...,"Best Restaurants in Gopalpura, Jaipur - Top 3 ...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",jaipurmetroroutes.com,https://www.jaipurmetroroutes.com,› areas › restaurants,1Book in Advance · 2Try Local Specialties · 3C...,Sharma Dhaba,https://www.jaipurmetroroutes.com/areas/gopalp...,Read more,NaN,NaN,NaN,NaN
6,https://www.proptiger.com/jaipur/gopalpura-533...,Restaurants in Gopalpura Jaipur - Best Multi-C...,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",PropTiger.com,https://www.proptiger.com,› jaipur › gopalpura-53318,Top Restaurants in Gopalpura Jaipur · · Ji Ha...,Harihant Bhojnalya,https://www.proptiger.com/jaipur/gopalpura-533...,Read more,NaN,NaN,NaN,NaN
7,https://www.venuelook.com/jaipur/locality/gopa...,"30 Best Restaurants in Gopalpura, Jaipur","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",VenueLook,https://www.venuelook.com,› ... › Restaurants in Jaipur,Find and book . Explore top party venues and R...,"best Restaurants in Gopalpura, Jaipur",NaN,NaN,https://www.venuelook.com/jaipur/locality/gopa...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////...",4.4,(790)
8,https://magicpin.in/india/Jaipur/Gopalpura/Res...,"Best Restaurants in Gopalpura, Jaipur - Magicpin","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",Magicpin,https://magicpin.in,› India › Jaipur › Gopalpura,· Ali Fresh Chicken · Arya Family Restaurant ·...,Neemroots Cafe Take Away,https://magicpin.in/india/Jaipur/Gopalpura/Res...,Read more,https://magicpin.in/india/Jaipur/Gopalpura/Res...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////...",NaN,NaN
9,https://www.tripadvisor.in/Restaurant_Review-g...,"TAPRI CENTRAL, Jaipur - Restaurant Reviews, Ph...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",Tripadvisor,https://www.tripadvisor.in,› Restaurant_Review-g304555...,NaN,NaN,NaN,NaN,NaN,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////...",NaN,NaN

In [103]:
# Rename all columns
df2 = df2.rename(columns={
    'zReHs href'  : 'Restaurant_URL',
    'LC20lb'      : 'Restaurant_Name',
    'XNo5Ab src'  : 'Logo_Image',
    'VuuXrf'      : 'Source_Platform',
    'qLRx3b'      : 'Platform_URL',
    'ylgVCe'      : 'Breadcrumb_Path',
    'VwiC3b'      : 'Restaurant_List',
    'VwiC3b 2'    : 'Featured_Restaurant',
    'vzmbzf href' : 'Read_More_URL',
    'vzmbzf'      : 'Read_More_Label',
    'kb0PBd href' : 'Redirect_URL',
    'uhHOwf src'  : 'Restaurant_Image',
    'yi40Hd'      : 'Rating',
    'RDApEe'      : 'Total_Reviews'
})

# Remove unwanted columns
df2 = df2.drop(columns=[
    'Logo_Image',
    'Platform_URL',
    'Breadcrumb_Path',
    'Read_More_URL',
    'Read_More_Label',
    'Restaurant_Image'
])

In [104]:
print("Columns:", df2.columns.tolist())
df2.head(2)

Columns: ['Restaurant_URL', 'Restaurant_Name', 'Source_Platform', 'Restaurant_List', 'Featured_Restaurant', 'Redirect_URL', 'Rating', 'Total_Reviews']

,Restaurant_URL,Restaurant_Name,Source_Platform,Restaurant_List,Featured_Restaurant,Redirect_URL,Rating,Total_Reviews
0,https://www.zomato.com/jaipur/gopalpura-restau...,"Gopalpura Restaurants, Jaipur",Zomato,"Gopalpura Restaurants, Jaipur · · Clayb.orn ·...",Up & Up,https://www.zomato.com/jaipur/gopalpura-restau...,NaN,NaN
1,https://www.justdial.com/Jaipur/Restaurants-in...,"Best Restaurants in Gopalpura Bypass, Jaipur",Justdial,"Best Restaurants in Gopalpura Bypass, Jaipur -...",Sabjiwalas,https://www.justdial.com/Jaipur/Restaurants-in...,4.0,"(3,44,646)"

In [105]:
# utf-8 → most common ✔
# latin1 → used for special cases
# df = pd.read_csv("data.csv", encoding="utf-8")

In [110]:
new_df = pd.read_csv("C:\\Users\\Admin\\pandas\\masoori _place.csv")
new_df

,tablescraper-selected-row,tablescraper-selected-row 2,tablescraper-selected-row href
0,NaN,NaN,NaN
1,"Discover the ethereal charm of Mussoorie, wher...",NaN,NaN
2,1. Lal Tibba - The Highest Point,NaN,NaN
3,", Lal Tibba stands as Mussoorie's highest poin...","Perched at 2,275 meters",NaN
4,Must Read:,Places To Visit in Jim Corbett National Park,https://www.tarangiresort.com/blog/places-to-v...
5,2. Kempty Falls - Nature's Cascade,NaN,NaN
6,"In the , Kempty Falls unfolded a mesmerizing t...",heart of Mussoorie,NaN
7,Must Read:,Mussoorie: A Breathtaking Vacation Destination...,https://www.tarangiresort.com/blog/Discover-Mu...
8,3. Gun Hill - A Historical Retreat,NaN,NaN
9,"Perched atop Mussoorie, Gun Hill echoes with t...",second-highest peak in the region,NaN
10,4. The Mall Road - Shop and Stroll,NaN,NaN
11,"The Mall Road, invites you to a . Lined with v...",delightful dance of shopping and strolling,NaN
12,Must Read:,Reasons Why You Should Choose Tarangi,https://www.tarangiresort.com/blog/top-10-reas...
13,5. Company Garden - Blooms and Serenity,NaN,NaN
14,Company Garden unveils a canvas of vibrant . A...,blooms and tranquil serenity,NaN
15,6. Mussoorie Lake - Serene Waterfront,NaN,NaN
16,unveils a haven of serenity. As I strolled alo...,Mussoorie Lake,NaN
17,Must Read:,Luxury Hotel in Mussoorie,https://www.tarangiresort.com/tarangi-mussoorie/
18,7. Benog Wildlife Sanctuary - Nature's Haven,NaN,NaN
19,The Benog Wildlife Sanctuary is nature's haven...,NaN,NaN
20,Must Read:,Best Resot Nearby Nainital,https://www.tarangiresort.com/
21,8. Landour - Colonial Charm,NaN,NaN
22,Landour is a colonial gem frozen in time. Cobb...,vintage charm,NaN
23,Must Read:,Places To Visit in Nainital,https://www.tarangiresort.com/blog/things-to-d...
24,9. Jharipani Falls - Hidden Gem,NaN,NaN
25,Jharipani Falls is Mussoorie's hidden treasure...,nature's melody,NaN
26,10. Cloud's End - Wilderness Retreat,NaN,NaN
27,"Mussoorie, Cloud's End is a . Surrounded by th...",haven of serenity,NaN
28,Must Read:,Meeting And Conference Halls Available,https://www.tarangiresort.com/tarangi-mussoori...
29,11. Nag Tibba - Trekking Adventure,NaN,NaN
30,Embarking on the Nag Tibba trek in the was an...,mystical hills of Mussoorie,NaN
31,Must Read:,Destination Wedding In Jim Corbett National Park,https://www.tarangiresort.com/blog/destination...
32,12. Camel's Back Road - A Leisurely Stroll,NaN,NaN
33,Camel's Back Road invites wanderers to a leisu...,haven for peace-seekers,NaN