In [148]:
import pandas as pd  

import os  
os.getcwd()

'C:\\Users\\Admin\\pandas'

In [149]:
df = pd.read_csv('C:\\Users\\Admin\\pandas\\placement - placement.csv')
df.sample()

    cgpa  resume_score  placed
83   7.6          8.08       1

In [150]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [151]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [152]:
df.info() # all  information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [153]:
df.describe() # statically  view of  data

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [154]:
top_left_corner_df  = df.iloc[:4,:3]
top_left_corner_df

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [155]:
df.loc[1:3,['cgpa','placed']]

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [156]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [157]:
s = df.dtypes
s

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [158]:
b = df.empty  # Returns True if the DataFrame has zero rows (completely empty)
              # Returns False if the DataFrame has one or more rows
b

False

In [159]:
df.isnull().sum() # fro check  missing value

cgpa            0
resume_score    0
placed          0
dtype: int64

In [160]:
df = df.dropna() # for  remove  missing  row  or  full  row remove

In [161]:
i = df.ndim # number of axes(it is 2)
i  #by  default  df  is  2d

2

In [162]:
d = df.shape  # shape = rows(n) ,columns(n)
d

(100, 3)

In [163]:
df.shape[0] # show  how  many  rows  in df  
df.shape[1] # show  how many  column in df

3

In [164]:
d = df.size  # rows count * columns count 
d            # df.size = total number of elements in DataFrame

300

In [165]:
h  = df.values  # df.values returns all data as a NumPy array without row and column labels
h

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [166]:
df2 = df.copy()

In [167]:
# assending  order  = min----->max
p = df.sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [168]:
# What is astype()?

# Used to change the data type of a column or entire DataFrame

In [169]:
# x = df.astype(int) 
# type  conversion 
df['cgpa'] = df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [170]:
df['cgpa'] = df['cgpa'].astype(str)
df.dtypes

cgpa             object
resume_score    float64
placed            int64
dtype: object

In [171]:
df['cgpa'] = df['cgpa'].astype(int)
df.dtypes

cgpa              int64
resume_score    float64
placed            int64
dtype: object

In [172]:
df.head()

   cgpa  resume_score  placed
0     8          6.52       1
1     6          5.17       0
2     8          8.86       1
3     6          7.27       1
4     7          7.30       1

In [173]:
df['resume_score'] = df['resume_score'].astype(int)

In [174]:
df.sample(3)

    cgpa  resume_score  placed
45     8             5       1
85     6             5       0
43     8             7       1

In [175]:
# w = df.abs() abs() returns the absolute value, converting negative numbers to positive."
# w

In [176]:
df['cgpa'] = df['cgpa'].add(1)

In [177]:
s = df.count()  #Count non-null values
s

cgpa            100
resume_score    100
placed          100
dtype: int64

In [178]:
s = df.max() #Count non-null values
s

cgpa            10
resume_score     9
placed           1
dtype: int64

In [179]:
# df['city'].max()  maximum city give  first letter  check  acording  to  alphabate    in string

In [180]:
g = df.filter(items=['cgpa','placed']) 
              #"Both return the same columns, but filter() provides more flexible selection options."
g
# or  
df[['cgpa','placed']] # second  option of filtering  


# if  want selected  rows  then  use  loc  and  iloc

    cgpa  placed
0      9       1
1      7       0
2      9       1
3      7       1
4      8       1
..   ...     ...
95     7       0
96     9       1
97     7       0
98     9       1
99     7       0

[100 rows x 2 columns]

In [181]:
s = df.filter(items=[5,6],axis=0) ###axis  =0  means row wise  operation  
s

   cgpa  resume_score  placed
5     9             6       1
6     6             7       0

In [182]:
s = df.filter(like = '5',axis=0)  
s

    cgpa  resume_score  placed
5      9             6       1
15     9             5       1
25     8             5       1
35     9             7       1
45     9             5       1
50     9             6       1
51     7             7       0
52     6             7       0
53     7             7       0
54     6             7       0
55     7             6       1
56     7             6       0
57     7             7       0
58     7             7       0
59     6             7       0
65     7             8       0
75     7             7       1
85     7             5       0
95     7             6       0

In [183]:
s = df.to_dict()
s

{'cgpa': {0: 9,
  1: 7,
  2: 9,
  3: 7,
  4: 8,
  5: 9,
  6: 6,
  7: 7,
  8: 7,
  9: 8,
  10: 7,
  11: 6,
  12: 7,
  13: 9,
  14: 8,
  15: 9,
  16: 9,
  17: 8,
  18: 6,
  19: 7,
  20: 6,
  21: 7,
  22: 7,
  23: 7,
  24: 9,
  25: 8,
  26: 7,
  27: 6,
  28: 8,
  29: 7,
  30: 8,
  31: 6,
  32: 6,
  33: 9,
  34: 9,
  35: 9,
  36: 9,
  37: 10,
  38: 7,
  39: 8,
  40: 9,
  41: 9,
  42: 7,
  43: 9,
  44: 6,
  45: 9,
  46: 6,
  47: 8,
  48: 6,
  49: 6,
  50: 9,
  51: 7,
  52: 6,
  53: 7,
  54: 6,
  55: 7,
  56: 7,
  57: 7,
  58: 7,
  59: 6,
  60: 6,
  61: 7,
  62: 6,
  63: 9,
  64: 8,
  65: 7,
  66: 9,
  67: 7,
  68: 7,
  69: 9,
  70: 8,
  71: 8,
  72: 8,
  73: 6,
  74: 6,
  75: 7,
  76: 10,
  77: 6,
  78: 6,
  79: 6,
  80: 8,
  81: 7,
  82: 8,
  83: 8,
  84: 6,
  85: 7,
  86: 7,
  87: 6,
  88: 9,
  89: 6,
  90: 6,
  91: 9,
  92: 6,
  93: 10,
  94: 9,
  95: 7,
  96: 9,
  97: 7,
  98: 9,
  99: 7},
 'resume_score': {0: 6,
  1: 5,
  2: 8,
  3: 7,
  4: 7,
  5: 6,
  6: 7,
  7: 6,
  8: 6,
  9: 7,
  10: 6,
  11: 6,
  12: 7,
  13: 5,
  14: 6,
  15: 5,
  16: 7,
  17: 8,
  18: 5,
  19: 8,
  20: 8,
  21: 7,
  22: 5,
  23: 7,
  24: 6,
  25: 5,
  26: 6,
  27: 6,
  28: 7,
  29: 7,
  30: 7,
  31: 7,
  32: 7,
  33: 7,
  34: 7,
  35: 7,
  36: 7,
  37: 8,
  38: 8,
  39: 6,
  40: 5,
  41: 5,
  42: 6,
  43: 7,
  44: 5,
  45: 5,
  46: 5,
  47: 8,
  48: 6,
  49: 6,
  50: 6,
  51: 7,
  52: 7,
  53: 7,
  54: 7,
  55: 6,
  56: 6,
  57: 7,
  58: 7,
  59: 7,
  60: 6,
  61: 7,
  62: 8,
  63: 7,
  64: 8,
  65: 8,
  66: 8,
  67: 6,
  68: 7,
  69: 9,
  70: 7,
  71: 8,
  72: 7,
  73: 6,
  74: 7,
  75: 7,
  76: 5,
  77: 6,
  78: 5,
  79: 7,
  80: 7,
  81: 6,
  82: 6,
  83: 8,
  84: 6,
  85: 5,
  86: 5,
  87: 5,
  88: 6,
  89: 7,
  90: 5,
  91: 6,
  92: 6,
  93: 7,
  94: 4,
  95: 6,
  96: 7,
  97: 7,
  98: 5,
  99: 6},
 'placed': {0: 1,
  1: 0,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 0,
  7: 0,
  8: 0,
  9: 1,
  10: 0,
  11: 0,
  12: 0,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 0,
  19: 1,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 1,
  25: 1,
  26: 0,
  27: 0,
  28: 1,
  29: 0,
  30: 1,
  31: 0,
  32: 0,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 0,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 0,
  45: 1,
  46: 0,
  47: 1,
  48: 0,
  49: 0,
  50: 1,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 1,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 1,
  62: 0,
  63: 1,
  64: 1,
  65: 0,
  66: 1,
  67: 1,
  68: 0,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 0,
  74: 0,
  75: 1,
  76: 1,
  77: 0,
  78: 0,
  79: 0,
  80: 1,
  81: 0,
  82: 1,
  83: 1,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 1,
  89: 0,
  90: 0,
  91: 1,
  92: 0,
  93: 1,
  94: 1,
  95: 0,
  96: 1,
  97: 0,
  98: 1,
  99: 0}}

In [184]:
s = df.to_string()

In [185]:
e = df.to_csv('new_df_df')

In [186]:
s = df.rename(columns = {'cgpa':'updated_cgpa','resume_score':'sem_mark'})
s# columns name rename

    updated_cgpa  sem_mark  placed
0              9         6       1
1              7         5       0
2              9         8       1
3              7         7       1
4              8         7       1
..           ...       ...     ...
95             7         6       0
96             9         7       1
97             7         7       0
98             9         5       1
99             7         6       0

[100 rows x 3 columns]

In [187]:
df['half']  = df['cgpa'].where(df['cgpa']>7,other = 0)
df.head(10)

   cgpa  resume_score  placed  half
0     9             6       1     9
1     7             5       0     0
2     9             8       1     9
3     7             7       1     0
4     8             7       1     8
5     9             6       1     9
6     6             7       0     0
7     7             6       0     0
8     7             6       0     0
9     8             7       1     8

In [188]:
df = pd.read_csv('C:\\Users\\Admin\\pandas\\covid_toy - covid_toy.csv')
df.sample()

    age gender  fever cough       city has_covid
78   11   Male  100.0  Mild  Bangalore       Yes

In [189]:
df.dropna()

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [190]:
df.groupby('has_covid').size()

has_covid
No     55
Yes    45
dtype: int64

In [191]:
# task :- 

# Create an Employee DataFrame in which you have (Emp_ID, Emp_Name, Department, Salary)
# Column and you have total 8 rows in your dataframe and you have to calculate :

# (1) Top 3 data
# (2) Bottom 4 data
# (3) Create a new column in which whose salary is greater than 20000 only shows 1 rest all are 0.
# (4) Check Staticaly view and info() of dataframe ?

In [192]:
d = {
    "Emp_ID":[101,102,103,104,105,106,107,108],
    "Emp_Name":['ajay','aman','pinku','tina','chinki','harsh','tarun','neelam'],
    "Department":['it','manager','client_issue','it','manager','client_issue','technistion','it'],
    "SaLary":[120000,5000,21000,120000,5000,21000,2500,120000]
}

In [193]:
df = pd.DataFrame(d)
df

   Emp_ID Emp_Name    Department  SaLary
0     101     ajay            it  120000
1     102     aman       manager    5000
2     103    pinku  client_issue   21000
3     104     tina            it  120000
4     105   chinki       manager    5000
5     106    harsh  client_issue   21000
6     107    tarun   technistion    2500
7     108   neelam            it  120000

In [194]:
df.head(3)

   Emp_ID Emp_Name    Department  SaLary
0     101     ajay            it  120000
1     102     aman       manager    5000
2     103    pinku  client_issue   21000

In [195]:
df.tail(4)

   Emp_ID Emp_Name    Department  SaLary
4     105   chinki       manager    5000
5     106    harsh  client_issue   21000
6     107    tarun   technistion    2500
7     108   neelam            it  120000

In [196]:
df['salary_greater_20000'] =  df['SaLary'].where(df['SaLary']>20000,other = 0)
df['salary_greater_20000'] =  df['salary_greater_20000'].where(df['salary_greater_20000']==0,other = 1)

In [197]:
df

   Emp_ID Emp_Name    Department  SaLary  salary_greater_20000
0     101     ajay            it  120000                     1
1     102     aman       manager    5000                     0
2     103    pinku  client_issue   21000                     1
3     104     tina            it  120000                     1
4     105   chinki       manager    5000                     0
5     106    harsh  client_issue   21000                     1
6     107    tarun   technistion    2500                     0
7     108   neelam            it  120000                     1

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Emp_ID                8 non-null      int64
 1   Emp_Name              8 non-null      object
 2   Department            8 non-null      object
 3   SaLary                8 non-null      int64
 4   salary_greater_20000  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes

In [199]:
df.describe()

          Emp_ID         SaLary  salary_greater_20000
count    8.00000       8.000000              8.000000
mean   104.50000   51812.500000              0.625000
std      2.44949   56898.366472              0.517549
min    101.00000    2500.000000              0.000000
25%    102.75000    5000.000000              0.000000
50%    104.50000   21000.000000              1.000000
75%    106.25000  120000.000000              1.000000
max    108.00000  120000.000000              1.000000